name: CI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential uuid-dev iasl git nasm gcc-aarch64-linux-gnu bc abootimg

    - name: Clone EDK2 repositories
      run: |
        git clone --depth 1 --branch edk2-stable202208 https://github.com/tianocore/edk2.git
        git -C edk2 submodule update --init --recursive --depth 1
        git init edk2-platforms
        git -C edk2-platforms remote add origin https://github.com/tianocore/edk2-platforms.git
        git -C edk2-platforms fetch --depth 1 origin 3c3b1168017073c2bb2d97336c5929ebae805be1
        git -C edk2-platforms checkout -B pinned-edk2-stable202208 FETCH_HEAD

    - name: Run firstrun.sh
      run: ./firstrun.sh

    - name: Run build.sh
      run: ./build.sh
